# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UnsplashDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UnsplashDemo

   pod 'SDWebImage', '~> 4.0'
pod "UnsplashKit/API" # Official API
pod "UnsplashKit/Source" # Source API


end
